added more tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,13 +21,13 @@ jobs:
           cache: npm
 
       - name: Install dependencies
-  run: npm ci --include=dev
+        run: npm ci --include=dev
 
       - name: Install Playwright Browsers
         run: npx playwright install --with-deps
 
       - name: Run Playwright tests
-  run: npm run test:ci || echo "TESTS_FAILED=1" >> $GITHUB_ENV
+        run: npm run test:ci || echo "TESTS_FAILED=1" >> $GITHUB_ENV
         env:
           CI: true
 
